// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

public enum BubbleType : sbyte
{
  normal = 0,
  event = 1,
};


}
