// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Bubbles : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Bubbles GetRootAsBubbles(ByteBuffer _bb) { return GetRootAsBubbles(_bb, new Bubbles()); }
  public static Bubbles GetRootAsBubbles(ByteBuffer _bb, Bubbles obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Bubbles __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fbs.pilot.Bubble? Bubbles(int j) { int o = __p.__offset(4); return o != 0 ? (fbs.pilot.Bubble?)(new fbs.pilot.Bubble()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BubblesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<fbs.pilot.Bubbles> CreateBubbles(FlatBufferBuilder builder,
      VectorOffset bubblesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Bubbles.AddBubbles(builder, bubblesOffset);
    return Bubbles.EndBubbles(builder);
  }

  public static void StartBubbles(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddBubbles(FlatBufferBuilder builder, VectorOffset bubblesOffset) { builder.AddOffset(0, bubblesOffset.Value, 0); }
  public static VectorOffset CreateBubblesVector(FlatBufferBuilder builder, Offset<fbs.pilot.Bubble>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBubblesVectorBlock(FlatBufferBuilder builder, Offset<fbs.pilot.Bubble>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartBubblesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fbs.pilot.Bubbles> EndBubbles(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fbs.pilot.Bubbles>(o);
  }
};


}
