// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

public enum Command : sbyte
{
  welcome = 0,
  ping = 1,
  bubble_get = 2,
  bubble_status = 3,
  player_get = 4,
  player_status = 5,
  game_ready = 6,
  game_start = 7,
  game_finish = 8,
};


}
