// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

public enum Data : byte
{
  NONE = 0,
  Bubble = 1,
  Bubbles = 2,
  Player = 3,
  Players = 4,
};


}
