// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

public enum PlayerStatus : sbyte
{
  idle = 0,
  ready = 1,
  game = 2,
};


}
