// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fbs.pilot
{

public enum Sender : sbyte
{
  server = 0,
  client = 1,
};


}
