# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pilot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Bubble(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bubble()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBubble(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bubble
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bubble
    def Uid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Bubble
    def PosCur(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = o + self._tab.Pos
            from fbs.pilot.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bubble
    def PosTarget(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from fbs.pilot.Vec2 import Vec2
            obj = Vec2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bubble
    def Speed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # Bubble
    def Type(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def BubbleStart(builder): builder.StartObject(5)
def Start(builder):
    return BubbleStart(builder)
def BubbleAddUid(builder, uid): builder.PrependInt32Slot(0, uid, 0)
def AddUid(builder, uid):
    return BubbleAddUid(builder, uid)
def BubbleAddPosCur(builder, posCur): builder.PrependStructSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(posCur), 0)
def AddPosCur(builder, posCur):
    return BubbleAddPosCur(builder, posCur)
def BubbleAddPosTarget(builder, posTarget): builder.PrependStructSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(posTarget), 0)
def AddPosTarget(builder, posTarget):
    return BubbleAddPosTarget(builder, posTarget)
def BubbleAddSpeed(builder, speed): builder.PrependFloat32Slot(3, speed, 0.0)
def AddSpeed(builder, speed):
    return BubbleAddSpeed(builder, speed)
def BubbleAddType(builder, type): builder.PrependInt8Slot(4, type, 0)
def AddType(builder, type):
    return BubbleAddType(builder, type)
def BubbleEnd(builder): return builder.EndObject()
def End(builder):
    return BubbleEnd(builder)