# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pilot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Bubbles(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Bubbles()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBubbles(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Bubbles
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Bubbles
    def Bubbles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.pilot.Bubble import Bubble
            obj = Bubble()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Bubbles
    def BubblesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Bubbles
    def BubblesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BubblesStart(builder): builder.StartObject(1)
def Start(builder):
    return BubblesStart(builder)
def BubblesAddBubbles(builder, bubbles): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bubbles), 0)
def AddBubbles(builder, bubbles):
    return BubblesAddBubbles(builder, bubbles)
def BubblesStartBubblesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartBubblesVector(builder, numElems):
    return BubblesStartBubblesVector(builder, numElems)
def BubblesEnd(builder): return builder.EndObject()
def End(builder):
    return BubblesEnd(builder)