# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pilot

class Command(object):
    welcome = 0
    ping = 1
    bubble_get = 2
    bubble_status = 3
    player_get = 4
    player_status = 5
    game_ready = 6
    game_start = 7
    game_finish = 8
    joycon = 9
    shoot = 10
    reload = 11
