# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pilot

class Data(object):
    NONE = 0
    Bubble = 1
    Bubbles = 2
    Player = 3
    Players = 4
    Joycon = 5
