# automatically generated by the FlatBuffers compiler, do not modify

# namespace: pilot

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Players(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Players()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayers(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Players
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Players
    def Players(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from fbs.pilot.Player import Player
            obj = Player()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Players
    def PlayersLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Players
    def PlayersIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PlayersStart(builder): builder.StartObject(1)
def Start(builder):
    return PlayersStart(builder)
def PlayersAddPlayers(builder, players): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(players), 0)
def AddPlayers(builder, players):
    return PlayersAddPlayers(builder, players)
def PlayersStartPlayersVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPlayersVector(builder, numElems):
    return PlayersStartPlayersVector(builder, numElems)
def PlayersEnd(builder): return builder.EndObject()
def End(builder):
    return PlayersEnd(builder)